<div class="modal-content">
<?php
$form = $this->formAuth;
$form->prepare();
$this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-warning" role="alert">')
    ->setMessageSeparatorString('')
    ->setMessageCloseString('</div>');
echo $this->form()->openTag($form);
?>
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="inscriptionModalLabel">Créez votre compte</h4>
</div>
<div class="modal-body">
    <p>Votre login : <?php echo $this->formText( $form->get('login') ); ?></p>
    <?php echo $this->formElementErrors()->render($form->get('login'));?>
    <p></p><?php echo $this->formCaptcha( $form->get('newUserCaptcha')); ?></p>
    <?php echo $this->formElementErrors()->render($form->get('newUserCaptcha'));?>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">s'inscrire</button>
</div>
<?php echo $this->form()->closeTag(); ?>
</div>
